In [1]:
import numpy as np

# reshape的使用
> - 根据给定的新形状重塑矩阵，新形状应该和原形状兼容
> - 新的形状必须包含与旧的形状相同数量的元素，这意味着两个形状的维度乘积必须相等。当使用 -1 参数时，与-1 相对应的维数将是原始数组的维数除以新形状中已给出维数的乘积，以便维持相同数量的元素

In [2]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])
a.shape

(2, 4)

In [3]:
a.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [4]:
a.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [5]:
a.reshape(-1,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
a.reshape(2,2,-1)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [8]:
a.reshape(2,-1,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

# Argpartition
> - 在数组中找到最大的 N 个元素
> - 高效地找到 N 个最大值的索引并返回 N 个值。在给出索引后，我们可以根据需要进行值排序

In [10]:
array = np.array([10, 7, 4, 3, 2, 2, 5, 9, 0, 4, 6, 0])
index = np.argpartition(array, -5)[-5:]
index

array([ 6,  1, 10,  7,  0])

In [11]:
array[index]

array([ 5,  7,  6,  9, 10])

In [12]:
np.sort(array[index])

array([ 5,  6,  7,  9, 10])

# Clip
> - 用于对数组中的值进行限制。给定一个区间范围，区间范围外的值将被截断到区间的边界上。例如，如果指定的区间是 [-1,1]，小于-1 的值将变为-1，而大于 1 的值将变为 1

In [13]:
array = np.array([10, 7, 4, 3, 2, 2, 5, 9, 0, 4, 6, 0])
np.clip(array,2,6)

array([6, 6, 4, 3, 2, 2, 5, 6, 2, 4, 6, 2])

In [14]:
np.clip(np.array([10, -1, 4, -3, 2, 2, 5, 9, 0, 4, 6, 0]),2,5)

array([5, 2, 4, 2, 2, 2, 5, 5, 2, 4, 5, 2])

# Extract
> - 从数组中提取符合条件的元素

In [16]:
arr = np.arange(10)
np.mod(arr, 3)==0

array([ True, False, False,  True, False, False,  True, False, False,
        True])

In [17]:
np.extract(np.mod(arr, 3)==0, arr)

array([0, 3, 6, 9])

In [18]:
np.extract(((arr > 2) & (arr < 8)), arr)

array([3, 4, 5, 6, 7])

# setdiff1d
> - 如何找到仅在 A 数组中有而 B 数组没有的元素

In [20]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.array([3,4,7,6,7,8,11,12,14])
np.setdiff1d(a,b)

array([1, 2, 5, 9])